### ISSUE TITLE
Correct GraphQL configuration support

### ISSUE THREAD

**Issue by shaughnlgh** [AntonShuvaev/jet-client-support#76]
**Describe the bug**
The plugin requires the JetBrains GraphQL plugin along with a `graphql.config.yml` file placed in the root of the project. The contents of the file is:

graphql.config.yml
```
schema: http://127.0.0.1:8080/graphql
```

This works fine for a single schema location, but when you need to add multiple project schema's, the JetClient plugin is unable to read from the config file.

**Steps to reproduce**
In order to add multiple project schema's, the correct format is:

graphql.config.yml
```
projects:
  local:
    schema: http://127.0.0.1:8080/graphql
  staging:
    schema: https://staging/graphql
  production:
    schema: https://production/graphql
```

Upon reloading, the JetClient plugin is unable to read the config file correctly and just shows blank options.

I can get this to work by doing the following:

graphql.config.yml
```
schema:
 - http://127.0.0.1:8080/graphql
 - https://staging/graphql
 - https://production/graphql
```

This displays correctly in the Jet Client plugin, however this specific format is used to stitch schema's, see https://the-guild.dev/graphql/config/docs/user/schema#multiple-files

See https://the-guild.dev/graphql/config/docs/user/usage#projects for the correct implementation.

**Environment information:**
- OS: macOs 14.4.1
- IDE version: Intellij Ultimate 2024.1.2
- plugin version: 2024.2.3-241
